export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const FETCH_TODOS = 'FETCH_TODOS';
export const SET_FETCHED_TODOS = 'SET_FETCHED_TODOS';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
